@startuml
!define RECTANGLE class

RECTANGLE User {
    +Username: String
    +Role: Enum {Admin, Doctor, Nurse, Technician, Patient}
    +Email: String
}

RECTANGLE Admin {
    +Username: String
    +Email: String
}

RECTANGLE Patient {
    +First Name: String
    +Last Name: String
    +Date of Birth: Date
    +Gender: String
    +Medical Record Number: String
    +Contact Information: String
    +Emergency Contact: String
}

RECTANGLE Staff {
    +First Name: String
    +Last Name: String
    +License Number: String
    +Specialization: String
    +Contact Information: String
    +Availability Slots: List<TimeSlot>
}


RECTANGLE OperationRequest {
    +ID: String
    +Patient ID: String
    +Doctor ID: String
    +Operation Type ID: String
    +Deadline Date: Date
    +Priority: Enum {Low, Medium, High}
}

RECTANGLE OperationType {
    +ID: String
    +Name: String
    +Required Staff by Specialization: List<String>
    +Estimated Duration: Time
}

RECTANGLE Appointment {
    +ID: String
    +Request ID: String
    +Room ID: String
    +Date and Time: DateTime
    +Status: Enum {Scheduled, Completed, Canceled}
}

RECTANGLE SurgeryRoom {
    +Room Number: String
    +Type: String
    +Capacity: Int
    +Current Status: Enum {Available, Occupied, Maintenance}
}

RECTANGLE TimeSlot {
    +Start Time: DateTime
    +End Time: DateTime
}

User --|> Admin
User --|> Patient
User --|> Staff
Staff "1" -- "many" TimeSlot
Patient "1" -- "many" Appointment
Appointment "1" -- "1" SurgeryRoom
Appointment "1" -- "1" OperationRequest
OperationRequest "1" -- "1" Patient
OperationRequest "1" -- "1" OperationType
OperationRequest "1" -- "1" Staff : Requested by Doctor
OperationType "1" -- "many" Staff : Requires

@enduml
