POST http://localhost:3001/medical-records/add-allergies/testPatient123
Content-Type: application/json

    {
        "allergen": "Dermetophagoides farinae",
        "severity": "High",
        "diagnosedDate": "2024-11-25T00:00:00.000Z",
        "notes": "Allergy to dust mites"
    }


###

GET http://localhost:3001/medical-records/

###

GET http://localhost:3001/api/medical-records/

###

POST http://localhost:3001/allergies/add-allergy
Content-Type: application/json

    {
        "allergen": "chocolate",
        "severity": "Low",
        "description": "Allergy to chocolate"
    }

###

GET http://localhost:3001/allergies/search?allergen=Derm