# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, test, and deploy ASP.Net Core app and React app to Azure Web App - 3dc-17

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test-backend:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore 3DC_G17.sln

      - name: Build with dotnet
        run: dotnet build 3DC_G17.sln --configuration Release --no-restore
        
      - name: Test with dotnet
        run: dotnet test 3DC_G17.sln --configuration Release --no-build

      - name: Publish
        run: dotnet publish dotnet-backend/DDDNetCore.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  build-and-test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: my-react-app/package-lock.json

      - name: Install Dependencies
        working-directory: my-react-app
        run: npm ci

      - name: Run Tests
        working-directory: my-react-app
        run: npm test -- --watchAll=false

      - name: Build React App
        working-directory: my-react-app
        run: npm run build

      - name: Upload React build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: my-react-app/build
          retention-days: 5

  deploy:
    runs-on: windows-latest
    needs: [build-and-test-backend, build-and-test-frontend]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download .NET app artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: myapp

      - name: Download React build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: myapp/wwwroot
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1F7FAC7122F4EF6BF5079A913248B92 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4C13091FA1A94C08B084A9FF04F42B83 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_318C47F2DD6A49F4A692618D459F89DF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '3dc-17'
          slot-name: 'Production'
          package: myapp
          
